# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20170604_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default='media/defaultBlogImage.png', upload_to=posts.models.Post.get_upload_to),
        ),
    ]
